version: '2'
services:
  api:
    build: 
      context: ..
      dockerfile: docker/api.dockerfile
  nginx:
    build: 
      context: ..
      dockerfile: docker/nginx.dockerfile
    ports:
     - "8000:80"